services:
  app:
    build:
      dockerfile: "./Dockerfile"
      context: ./
    container_name: web
    environment:
      APP_CONFIG__DB__URL: "postgresql+asyncpg://user:password@pg:5432/user"
    ports:
      - "5050:8000"
    depends_on:
      - pg

  pg:
    image: postgres
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"